
// 工事の時期 の選択肢
// 市区町村 の選択肢
list[{
  name: "calc",
  name2: "相場の計算",
  msg0: [
    "２つの方法で相場を計算することができます。",
    "どちらがご希望に近いですか？",
  ],
  msg: [],
  options: [],
  selected: "",
  type: "type0",
  answerType: "need",
  show: [],
},
{
  name: "bathType",
  name2: "お風呂の形式",
  msg0: [],
  msg: ["希望されるお風呂は、どのような形式ですか？"],
  // options: [{ a: 'ユニットバス', b: 'タイル貼り', c: 'わからない' }],
  options: ["ユニットバス", "タイル貼り", "わからない"],
  selected: "",
  type: "type1",
  answerType: "need",
  show: [],
},
{
  name: "bathSize",
  name2: "お風呂の大きさ",
  msg0: [],
  msg: ["希望されるお風呂の大きさは、どのくらいですか？"],
  options: ["２畳未満", "２畳以上", "わからない"],
  selected: "",
  type: "type1",
  answerType: "need",
  show: [],
},
{
  name: "bathShape",
  name2: "浴槽の形",
  msg0: ["浴槽まわりの希望をお伺いします。"],
  msg: [
    "湯船につかる頻度が多い場合は、浴槽の形が重要です。",
    "浴槽の形にこだわりはありますか？",
  ],
  options: ["広さ重視", "節水重視", "特になし"],
  selected: "",
  type: "type3",
  answerType: "need",
  show: [],
},
{ name: 'keepWarm',
  name2: '保温効果',
  msg0: [],
  msg: ['お湯の冷めにくい、保温効果のある浴槽をご希望されますか？'],
  options: [{ a: 'はい', b: '興味がある', c: 'いいえ' }],
  selected: [],
  type: 'type1',
  show: [],
},
{
  name: 'bubbleJet',
  name2: 'バブルバス・ジェットバス',
  msg0: [],
  msg: ['リラックス・マッサージ効果のある、バブルバス・ジェットバスをご希望されますか？'],
  options: [{ a: 'はい', b: '興味がある', c: 'いいえ' }],
  selected: [],
  type: 'type1',
  show: [],
},
{
  name: 'audio',
  name2: 'オーディオの設置',
  msg0: [],
  msg: ['お風呂に埋込み型のオーディオを設置すると、音の広がりがよく、また見た目もスッキリします。', 'お風呂にオーディオの設置を希望されますか？'],
  options: [{ a: 'はい', b: '興味がある', c: 'いいえ' }],
  selected: [],
  type: 'type2',
  show: [],
},
{
  name: 'tv',
  name2: 'テレビの設置',
  msg0: [],
  msg: ['ゆったりお湯に浸かりながら、最大24インチの大迫力の画面でテレビを楽しむこともできます。', 'お風呂にテレビの設置を希望されますか？'],
  options: [{ a: 'はい', b: '興味がある', c: 'いいえ' }],
  selected: [],
  type: 'type2',
  show: [],
},
{
  name: 'light',
  name2: '機能的な照明',
  msg0: [],
  msg: ['設置する照明にこだわると、利用シーンに合わせて浴室の雰囲気を手軽に変えることができます。','機能的な照明をご希望されますか？'],
  options: [{ a: 'はい', b: '興味がある', c: 'いいえ' }],
  selected: [],
  type: 'type2',
  show: [],
},
{
  name: 'reheat',
  name2: '追い焚き機能',
  msg0: [],
  msg: ['湯船に浸かる人が複数いたり、利用時間がバラバラな場合は、追い焚き機能が便利です。', '追い焚き機能をご希望されますか？'],
  options: [{ a: 'はい', b: '興味がある', c: 'いいえ' }],
  selected: [],
  type: 'type2',
  show: [],
},
{
  name: 'forApp',
  name2: 'アプリ対応',
  msg0: [],
  msg: ['お湯はりや浴室暖房などをスマートフォンアプリで操作できるお風呂があります。', 'アプリ対応のお風呂をご希望されますか？'],
  options: [{ a: 'はい', b: '興味がある', c: 'いいえ' }],
  selected: [],
  type: 'type2',
  show: [],
},
{
  name: 'showerHead',
  name2: 'シャワーヘッド',
  msg0: ['つづいて、洗い場など浴室全体の希望をお伺いします'],
  msg: ['シャワーヘッドを変更することで、節水して水道代を抑えながら、適度な水圧による刺激を得ることができます。', 'シャワーヘッドは機能的なものをご希望されますか？'],
  options: [{ a: 'はい', b: '興味がある', c: 'いいえ' }],
  selected: [],
  type: 'type3',
  show: [],
},
{
  name: 'bodyShower',
  name2: 'ボディシャワー',
  msg0: [],
  msg: ['全身にくまなくお湯を当ててくれるボディシャワーを利用することで、忙しい時のシャワーだけでもしっかりと体を温めることができます。', '通常のシャワーに加えて、ボディシャワーの設置もご希望されますか？'],
  options: [{ a: 'はい', b: '興味がある', c: 'いいえ' }],
  selected: [],
  type: 'type2',
  show: [],
},
{
  name: 'barrierFree',
  name2: 'バリアフリー',
  msg0: [],
  msg: ['浴室で不意の事故がおきないよう、年配の方でも安全に入浴できるお風呂を希望される方が増えています。', '段差の解消や手すりの設置など、バリアフリーなお風呂を希望されますか？'],
  options: [{ a: 'はい', b: '興味がある', c: 'いいえ' }],
  selected: [],
  type: 'type2',
  show: [],
},
{
  name: 'wallCabinet',
  name2: '壁面棚',
  msg0: [],
  msg: ['洗い場のカウンターや、小物収納ができる壁面棚を希望しますか？'],
  options: [{ a: 'はい', b: '興味がある', c: 'いいえ' }],
  selected: [],
  type: 'type1',
  show: [],
},
{
  name: 'mistSauna',
  name2: 'ミストサウナ',
  msg0: [],
  msg: ['ミストサウナとは、室内に蒸気をたっぷり充満させてじんわり体を温めるサウナです。室内の温度が40～60度ほどなので、設備さえあれば自宅の浴室でも楽しむことができます。', 'お風呂にミストサウナの設置を希望されますか？'],
  options: [{ a: 'はい', b: '興味がある', c: 'いいえ' }],
  selected: [],
  type: 'type2',
  show: [],
},
{
  name: 'floorHeating',
  name2: '床暖房',
  msg0: [],
  msg: ['床暖房機能があると、浴室の床が乾きやすくなり、カビやぬめりの発生を防ぐことができます。また、冬場のヒートショックを防ぐ効果もあります。', '床暖房の設置はご希望されますか？'],
  options: [{ a: 'はい', b: '興味がある', c: 'いいえ' }],
  selected: [],
  type: 'type2',
  show: [],
},
{
  name: 'autoWash',
  name2: '自動洗浄のついた浴槽',
  msg0: ['つぎに、入浴以外でのお風呂の活用について、お伺いします。'],
  msg: ['掃除の手間を減らすため、入浴後、自動で浴槽を洗浄してくれる機能があります。', '自動洗浄のついた浴槽をご希望されますか？'],
  options: [{ a: 'はい', b: '興味がある', c: 'いいえ' }],
  selected: [],
  type: 'type3',
  show: [],
},
{
  name: 'removeBacteria',
  name2: '入浴後の除菌機能',
  msg0:[],
  msg: ['浴室の掃除の負担をへらすため、入浴後、床を水流で自動洗浄し、除菌する機能があります。', '掃除の負担をへらすために、この機能をご希望されますか？'],
  options: [{ a: 'はい', b: '興味がある', c: 'いいえ' }],
  selected: [],
  type: 'type2',
  show: [],
},
{
  name: 'bathroomDryer',
  name2: '浴室乾燥機',
  msg0:[],
  mag: ['浴室乾燥機能があると、天候や季節、花粉などを気にせずに、浴室で洗濯物を乾かすことができます。暖房とセットのため、冬場のヒートショックを防ぐ効果もあります。', '浴室乾燥機をご希望されますか？'],
  options: [{ a: 'はい', b: '興味がある', c: 'いいえ' }],
  selected: [],
  type: 'type2',
  show: [],
},
{
  name: 'currentType',
  name2: '今のお風呂の形式',
  msg0: ['今のお風呂の状況によって、工事費用が変わってきます。'],
  msg: ['今のお風呂は、どのようなつくりになっていますか？'],
  options: [{ a: 'ユニットバス', b: 'タイル貼り', c: 'わからない' }],
  selected: [],
  type: 'type2',
  answerType: "need",
  current: 'true',
  show: [],
},
  {
  name: 'yearOfUse',
  name2: '使用年数',
  msg0: [],
  msg: ['ご使用年数は、どのくらいですか？'],
  options: [{ a: '1~10年', b: '10~20年', c: '20年~', d: '0年(購入前)' }],
  selected: [],
  type: 'type1',
  answerType: "need",
  current: 'true',
  show: [],
},
{
  name: 'window',
  name2: '浴室に窓',
  msg0: [],
  msg: ['浴室に窓はありますか？'],
  options: [{ a: 'ある', b: 'ない'}],
  selected: [],
  type: 'type1',
  current: 'true',
  show: [],
},
{
  name: 'placeOfFan',
  name2: '換気扇の場所',
  msg0: [],
  msg: ['換気扇は、どこについていますか？'],
  options: [{ a: '天井', b: '窓'}],
  selected: [],
  type: 'type1',
  answerType: "need",
  current: 'true',
  show: [],
},
{
  name: 'constPeriod',
  name2: '工事の時期',
  msg0: [],
  msg: ['工事の時期はお決まりですか？'],
  options: [{ a: '1~10年', b: '10~20年', c: '20年~', d: '0年(購入前)' }],
  selected: [],
  type: 'type1',
  answerType: "need",
  current: 'true',
  show: [],
},
{
  name: 'budget',
  name2: '予算',
  msg0: [],
  msg: ['予算はいくらですか？'],
  options: [{ a: '50万円未満', b: '50~80万円', c: '80~150万円', d: '150万円以上' }],
  selected: [],
  type: 'type1',
  answerType: "need",
  current: 'true',
  show: [],
},
{
  name: 'estimate',
  name2: '見積もり',
  msg0: [],
  msg: ['見積もりはお持ちですか？'],
  options: [{ a: '持っていない', b: '1社', c: '2社', d: '3社以上' }],
  selected: [],
  type: 'type1',
  answerType: "need",
  current: 'true',
  show: [],
},
{
  name: 'address',
  name2: '物件の場所',
  msg0: [],
  msg: ['物件の場所はどちらになりますか？'],
  options: [{ a: '北海道・東北', b: '関東', c: '北陸・甲信越', d: '関西', d: '中国', d: '四国' }],
  optionsA: [{ a: '北海道', b: '青森県', c: '岩手県', d: '宮城県', e: '秋田県', f: '山形県' }],
  optionsB: [{ a: '茨城県', b: '栃木県', c: '群馬県', d: '千葉県', e: '東京都', f: '神奈川県' }],
  optionsC: [{ a: '新潟県', b: '富山県', c: '石川県', d: '福井県', e: '山梨県', f: '長野県', g: '新潟県' }],
  optionsD: [{ a: '大阪府', b: '京都府', c: '兵庫県', d: '奈良県', e: '滋賀県', f: '和歌山県'}],
  optionsE: [{ a: '鳥取県', b: '島根県', c: '岡山県', d: '広島県', e: '山口県'}],
  optionsF: [{ a: '愛媛県', b: '香川県', c: '高知県', d: '徳島県'}],
  selected: [],
  type: 'type1',
  answerType: "need",
  branch: true,
  current: 'true',
  show: [],
},
{
  name: 'contractor',
  name2: 'リフォーム会社決まっているか',
  msg0: ['31個の入力ありがとうございました。', '最後になりますが、補助金が出るか確認いたします。'],
  msg: ['国の補助金事業「長期優良住宅化リフォーム推進事業」によって、補助金が出る場合があります。', 'リフォーム会社はすでにお決まりですか？'],
  options: [{ a: 'はい', b: 'いいえ'}],
  selected: [],
  type: 'type3',
  current: 'true',
  show: [],
},
{
  name: 'nursingCare',
  name2: '家族に要支援または要介護認定',
  msg0: [],
  msg: ['介護保険を利用した補助金があります。', '要支援または要介護認定されている方は、ご家族にいらっしゃいますか？'],
  options: [{ a: 'はい', b: 'いいえ'}],
  selected: [],
  type: 'type1',
  current: 'true',
  show: [],
},
  // はい
{
  name: 'municipalities',
  name2: '市区町村',
  msg0: [],
  msg: ['市区町村によって補助金が出る可能性があります。市区町村はどちらになりますか？'],
  options: [],
  selected: [],
  type: 'type1',
  current: 'true',
  show: [],
},
{
  name: 'telNumber',
  name2: '電話番号（ショートメッセージ）',
  msg0: ['ご回答ありがとうございました。56分30秒ほどかかりましたが、あと少しです。', '現在、いただいた条件にて私の方で急ぎ算定しております。あと30秒ほどで結果を送付しますので、送付先の入力をお願いします。'],
  msg: ['算定完了しました。送付先の入力をお願いします。'],
  selected: [],
  type: 'type3',
  current: 'true',
  show: [],
},
],
